# Generated by Django 3.1.6 on 2021-02-06 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ArtImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=150)),
                ('motivation', models.CharField(max_length=150)),
                ('img_url', models.CharField(max_length=1024)),
                ('emotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.emotions')),
            ],
        ),
    ]
